package com.example.demo;

public class IC_ES_MON_PER_MAG_COURT {

	String  YRMON, BAL_OF_PREV_MONTH, CASES_FILED_PDB_OFF,CASES_FILED_MOB_COURT,CASES_FILED_TOTAL,NO_OF_PER_JAILED,
	NO_OF_PER_FINED, NO_OF_PER_FINE_OR_JAIL,OTHERS, CASE_FINA_TOTAL, NO_OF_PER_REDEMPTION, NO_OF_PER_JUDGMENT, DC_ILLEGAL_CON,
	 NO_OF_MOB_COURT_CONDU,FINES_REALISED_TK, BAL_NOS;

	public IC_ES_MON_PER_MAG_COURT(String yRMON, String bAL_OF_PREV_MONTH, String cASES_FILED_PDB_OFF,
			String cASES_FILED_MOB_COURT, String cASES_FILED_TOTAL, String nO_OF_PER_JAILED, String nO_OF_PER_FINED,
			String nO_OF_PER_FINE_OR_JAIL, String oTHERS, String cASE_FINA_TOTAL, String nO_OF_PER_REDEMPTION,
			String nO_OF_PER_JUDGMENT, String dC_ILLEGAL_CON, String nO_OF_MOB_COURT_CONDU, String fINES_REALISED_TK,
			String bAL_NOS) {
		super();
		YRMON = yRMON;
		BAL_OF_PREV_MONTH = bAL_OF_PREV_MONTH;
		CASES_FILED_PDB_OFF = cASES_FILED_PDB_OFF;
		CASES_FILED_MOB_COURT = cASES_FILED_MOB_COURT;
		CASES_FILED_TOTAL = cASES_FILED_TOTAL;
		NO_OF_PER_JAILED = nO_OF_PER_JAILED;
		NO_OF_PER_FINED = nO_OF_PER_FINED;
		NO_OF_PER_FINE_OR_JAIL = nO_OF_PER_FINE_OR_JAIL;
		OTHERS = oTHERS;
		CASE_FINA_TOTAL = cASE_FINA_TOTAL;
		NO_OF_PER_REDEMPTION = nO_OF_PER_REDEMPTION;
		NO_OF_PER_JUDGMENT = nO_OF_PER_JUDGMENT;
		DC_ILLEGAL_CON = dC_ILLEGAL_CON;
		NO_OF_MOB_COURT_CONDU = nO_OF_MOB_COURT_CONDU;
		FINES_REALISED_TK = fINES_REALISED_TK;
		BAL_NOS = bAL_NOS;
	}

	public String getYRMON() {
		return YRMON;
	}

	public void setYRMON(String yRMON) {
		YRMON = yRMON;
	}

	public String getBAL_OF_PREV_MONTH() {
		return BAL_OF_PREV_MONTH;
	}

	public void setBAL_OF_PREV_MONTH(String bAL_OF_PREV_MONTH) {
		BAL_OF_PREV_MONTH = bAL_OF_PREV_MONTH;
	}

	public String getCASES_FILED_PDB_OFF() {
		return CASES_FILED_PDB_OFF;
	}

	public void setCASES_FILED_PDB_OFF(String cASES_FILED_PDB_OFF) {
		CASES_FILED_PDB_OFF = cASES_FILED_PDB_OFF;
	}

	public String getCASES_FILED_MOB_COURT() {
		return CASES_FILED_MOB_COURT;
	}

	public void setCASES_FILED_MOB_COURT(String cASES_FILED_MOB_COURT) {
		CASES_FILED_MOB_COURT = cASES_FILED_MOB_COURT;
	}

	public String getCASES_FILED_TOTAL() {
		return CASES_FILED_TOTAL;
	}

	public void setCASES_FILED_TOTAL(String cASES_FILED_TOTAL) {
		CASES_FILED_TOTAL = cASES_FILED_TOTAL;
	}

	public String getNO_OF_PER_JAILED() {
		return NO_OF_PER_JAILED;
	}

	public void setNO_OF_PER_JAILED(String nO_OF_PER_JAILED) {
		NO_OF_PER_JAILED = nO_OF_PER_JAILED;
	}

	public String getNO_OF_PER_FINED() {
		return NO_OF_PER_FINED;
	}

	public void setNO_OF_PER_FINED(String nO_OF_PER_FINED) {
		NO_OF_PER_FINED = nO_OF_PER_FINED;
	}

	public String getNO_OF_PER_FINE_OR_JAIL() {
		return NO_OF_PER_FINE_OR_JAIL;
	}

	public void setNO_OF_PER_FINE_OR_JAIL(String nO_OF_PER_FINE_OR_JAIL) {
		NO_OF_PER_FINE_OR_JAIL = nO_OF_PER_FINE_OR_JAIL;
	}

	public String getOTHERS() {
		return OTHERS;
	}

	public void setOTHERS(String oTHERS) {
		OTHERS = oTHERS;
	}

	public String getCASE_FINA_TOTAL() {
		return CASE_FINA_TOTAL;
	}

	public void setCASE_FINA_TOTAL(String cASE_FINA_TOTAL) {
		CASE_FINA_TOTAL = cASE_FINA_TOTAL;
	}

	public String getNO_OF_PER_REDEMPTION() {
		return NO_OF_PER_REDEMPTION;
	}

	public void setNO_OF_PER_REDEMPTION(String nO_OF_PER_REDEMPTION) {
		NO_OF_PER_REDEMPTION = nO_OF_PER_REDEMPTION;
	}

	public String getNO_OF_PER_JUDGMENT() {
		return NO_OF_PER_JUDGMENT;
	}

	public void setNO_OF_PER_JUDGMENT(String nO_OF_PER_JUDGMENT) {
		NO_OF_PER_JUDGMENT = nO_OF_PER_JUDGMENT;
	}

	public String getDC_ILLEGAL_CON() {
		return DC_ILLEGAL_CON;
	}

	public void setDC_ILLEGAL_CON(String dC_ILLEGAL_CON) {
		DC_ILLEGAL_CON = dC_ILLEGAL_CON;
	}

	public String getNO_OF_MOB_COURT_CONDU() {
		return NO_OF_MOB_COURT_CONDU;
	}

	public void setNO_OF_MOB_COURT_CONDU(String nO_OF_MOB_COURT_CONDU) {
		NO_OF_MOB_COURT_CONDU = nO_OF_MOB_COURT_CONDU;
	}

	public String getFINES_REALISED_TK() {
		return FINES_REALISED_TK;
	}

	public void setFINES_REALISED_TK(String fINES_REALISED_TK) {
		FINES_REALISED_TK = fINES_REALISED_TK;
	}

	public String getBAL_NOS() {
		return BAL_NOS;
	}

	public void setBAL_NOS(String bAL_NOS) {
		BAL_NOS = bAL_NOS;
	}

	@Override
	public String toString() {
		return "IC_ES_MON_PER_MAG_COURT [YRMON=" + YRMON + ", BAL_OF_PREV_MONTH=" + BAL_OF_PREV_MONTH
				+ ", CASES_FILED_PDB_OFF=" + CASES_FILED_PDB_OFF + ", CASES_FILED_MOB_COURT=" + CASES_FILED_MOB_COURT
				+ ", CASES_FILED_TOTAL=" + CASES_FILED_TOTAL + ", NO_OF_PER_JAILED=" + NO_OF_PER_JAILED
				+ ", NO_OF_PER_FINED=" + NO_OF_PER_FINED + ", NO_OF_PER_FINE_OR_JAIL=" + NO_OF_PER_FINE_OR_JAIL
				+ ", OTHERS=" + OTHERS + ", CASE_FINA_TOTAL=" + CASE_FINA_TOTAL + ", NO_OF_PER_REDEMPTION="
				+ NO_OF_PER_REDEMPTION + ", NO_OF_PER_JUDGMENT=" + NO_OF_PER_JUDGMENT + ", DC_ILLEGAL_CON="
				+ DC_ILLEGAL_CON + ", NO_OF_MOB_COURT_CONDU=" + NO_OF_MOB_COURT_CONDU + ", FINES_REALISED_TK="
				+ FINES_REALISED_TK + ", BAL_NOS=" + BAL_NOS + "]";
	}
	
	
}
